services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - './:/opt/app'
  server:
    image: nginx:stable-alpine
    volumes:
      - './public/:/opt/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${APP_PORT}:80'
    depends_on:
      - php